### ISSUE TITLE
Insomnia should respect system-wide font anti-aliasing (AA) settings

### ISSUE THREAD

**Issue by erlangparasu** [Kong/insomnia#1119]
- Insomnia Version: 6.0.2
- Operating System: Windows

## Details

Disable font antialiasing

**Comment by gschier** [comment]
Please provide more information on what this issue means and why it's imporant.

**Comment by erlangp** [comment]
iam using windows & i disable antialiasing for windows.. i expect the insomnia disabled font antialiasing too..

**Comment by denisftw** [comment]
@gschier 

The application currently ignores system-wide anti-aliasing settings. The idea is that if the user disables it system-wide, all applications should respect it and not render any anti-aliased (blurry) fonts. Most Electron-based apps including Postman or TestMace actually respect that; the problem is that both aforementioned apps use very specific Web fonts which are [impossible to change](https://github.com/postmanlabs/postman-app-support/issues/4142) and they look pretty terrible without anti-aliasing. The irony is that your app actually allows to change the font itself but since it messes with AA, it's just as bad (actually worse).

**Comment by gschier** [comment]
This should be possible to support. I don't think the fact that Insomnia allows the user to change the font interferes with anti-aliasing. 

I assume it's some sort of flag we can toggle, either in CSS or Electron itself. Does anyone want to make an attempt at this?

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.
