### ISSUE TITLE
[Feature Request] – Do not strip comments when Prettify

### ISSUE THREAD

**Issue by Matan** [Kong/insomnia#1124]
- Insomnia Version: 6.0.2 (snap)
- Operating System: Ubuntu 18.04

About window info:
Version 6.0.2
Shell 1.8.7
Node 8.2.1
V8 5.9.211.38
Architecture x64

libcurl/7.59.0 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.31.

## Details

When pressing "Prettify GraphQL" all comments are removed. It would be good not strip them as comments they can provide essential context between team members.

Thanks!!

**Comment by obukhov** [comment]
Faced the same issue. Any plans to improve on this?

**Comment by lukepighetti** [comment]
Requesting triage of this issue. Comment stripping is not ideal for us since we markup field integration status on the frontend side of things.

<img width="409" alt="Screen Shot 2020-07-22 at 1 52 01 PM" src="https://user-images.githubusercontent.com/666539/88210657-86c17080-cc22-11ea-9ed3-83dcf60856ed.png">

**Comment by coderich** [comment]
Facing the same issue

**Comment by dimitropoulos** [comment]
From what I can tell, the reason this happens is that we print it using the graphql utility.  https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.js#L366.

It happens to be that graphql.org is down right now, as is prettier.io (?? as confirmed by downforeveryoneorjustme.com and 3 of our teammates in different regions... eek..).

On a whim, I did update the graphql dependency to latest (15.5) to see if that made a difference (it didn't).  From there I think the next step has to be to look into a better solution for this.  It makes total sense that the AST parsing may ignore comments.  I wish it didn't but if you're writing a parser this kind of thing often is ignored (along with whitespace which is the reason prettier can sometimes have issues).

On that note, I think we may be able to format this with prettier (rather than parsing it and printing the output of the parse).

There are other issues this would solve (e.g. https://github.com/Kong/insomnia/issues/2301, https://github.com/Kong/insomnia/issues/2600).

**Comment by dimitropoulos** [comment]
if you want more info on this, check out https://github.com/graphql/graphiql/issues/555 and https://github.com/graphql/graphiql/pull/578

**Comment by dimitropoulos** [comment]
this should be fixed by https://github.com/Kong/insomnia/pull/4022 which should be in the next release
