### ISSUE TITLE
[Feature Request] Edit Variables values manually in interface

### ISSUE THREAD

**Issue by bbbco** [Kong/insomnia#1181]
- Insomnia Version: 6.0.2
- Operating System: Linux Mint 19

## Details

I'd like to arbitrarily modify/edit the values of variables when I use them inside the interface. Currently, if I want to modify them, I have to do so inside the manage environments section. However, if I click on the variable inside the interface, it shows an "Edit Variable" dialog with a read-only text field of the current value. I'd like to be able to modify this value. Of course, I understand that when you consider sub-environments, the question come up, where should the new value be applied to (base env, or one of the sub envs?). I imagine another option would be made available in the dialog allowing the user to choose what to do.

**Comment by soderluk** [comment]
I have thought about the same thing. I have different ID's that I want to use as the {{ id }} field, and whenever I create a new item in the db, I'd like to edit the new ID in the next `GET /read/{{ id }}` request that I'm going to use. Now the edit variable popup doesn't really do what it says, but it gives the option to _change_ a variable.

**Comment by soderluk** [comment]
This would be a good feature, anyone taking this up?

**Comment by natebrunette** [comment]
This would be great. I would assume it would edit whichever value it's pulling from. So in the case of sub-environments, it would modify the sub-environment if the variable exists, otherwise the base.

**Comment by spider4216** [comment]
I wanted to create feature request to offer possibility to edit variables in modal dialog and suddenly found that other users have already created this issue. For me this feature will be very useful. Edit variable in modal dialog will be able to make manage variables function more friendly and conveniently

**Comment by nkl90** [comment]
This is a very useful feature, please add it!

**Comment by KennethWussmann** [comment]
@bbbco I would like to implement this feature, but I could need some guidance.
I couldn't find a clean way of getting the environment id of the variable being edited in the `VariableEditor`. 
Only the name of the environment which is not unique.
Thanks.

**Comment by gschier** [comment]
There is a map of environment names generated here: 

https://github.com/getinsomnia/insomnia/blob/bba03d0eab34e29ec4f9fdb2d6dca4f82ddc1225/packages/insomnia-app/app/common/render.js#L217-L241

There are some problems with it though, like it does not work with nested variables (#1288). We can likely ignore this one for now and just not show the ability to edit if we cannot infer the environment.

Here are the steps I'd take to do this but this is just a suggestion:

1. Include the environment ID in the name map
2. In the variable editor component, add another field for the variable's pre-rendered value
3. Provide a `<PromptButton>` beside the new field to rename the value in it's environment
4. Show a confirmation dialog to the user to make it clear which environment is being modified
5. Make the modifications

In my opinion, step 5 is the scary part. It would be very easy for a bug to accidentally wipe out a user's environment.

Let me know what you think!

**Comment by gschier** [comment]
Also, as usual, don't worry about the UI/UX too much if you don't want to. If you can put together a barebones UI, I can tweak things after.

**Comment by KennethWussmann** [comment]
Hey! Thanks for the suggestions.

Okay I can add the id to the `keySource`, but it will always only be possible to edit root-level variables like:
```JSON
{
  "USER_ID": "123"
}
```
and not something like:
```JSON
{
  "PARAM": {
    "USER_ID": "123"
  }
}
```
Because the `keySource` only holds the root-level variables with the corresponding environment: 
https://github.com/getinsomnia/insomnia/blob/bba03d0eab34e29ec4f9fdb2d6dca4f82ddc1225/packages/insomnia-app/app/common/render.js#L222
Would be fine for me, but maybe contradictory for the user that he can edit the values for `{{ USER_ID }}` but not for `{{ PARAM.USER_ID }}`.

I think nested variables might not be that big of a problem, when the field to edit a variable value is completely un-rendered and just contains plain `{{VARIABLE}}` expressions:
![](https://i.imgur.com/6pgoXDk.png)

Actually, I don't know where the confirmation dialog should go. I think the `Edit Variable` modal is fairly easy to understand and the environment that's being edited is written right above the input field. Maybe it should say something like `Save` instead of `Done` and with a `Cancel` button (on the left). So, only pressing `Save` would override something in the environment.

Modification should not break something, because only root-level entries of the JSON can be edited and not sub-objects. Or are you scared of something I'm not aware of?

**Comment by gschier** [comment]
Ya, I wouldn't worry about nested variables for now.

I hesitate having a cancel/save button where the Done button is because all other dialogs (eg. environment editor) saves as you type. Having this one work differently would likely be confusing even though it makes sense in isolation.

What about something like having the save button inline with where you change the value?

![image](https://user-images.githubusercontent.com/587576/57500840-f021c180-72b2-11e9-9256-b7b34bddf0c3.png)

**Comment by alexsimpson440dev** [comment]
Anymore traction on this?

**Comment by bbbco** [comment]
indeed ... how is this feature looking?
