### ISSUE TITLE
[Bug] Can't retrieve schema for GraphQL

### ISSUE THREAD

**Issue by rolurq** [Kong/insomnia#1272]
- Insomnia Version: 6.2.0
- Operating System: Linux knight 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux

## Details
Insomnia fails to retrieve the GraphQl schema. It shows this error

![schema](https://user-images.githubusercontent.com/13684824/48922937-293ab680-ee78-11e8-9c85-d6a3d4da7940.png)

I took the graphql body in the request sent by insomnia and tried it in Insomnia itself and it works.

![test](https://user-images.githubusercontent.com/13684824/48922946-38b9ff80-ee78-11e8-98ad-5290f127bd6e.png)

So I guess the issue must be in the code that works with the fetched schema.

**Comment by gschier** [comment]
Would you be able to provide a public GraphQL endpoint to test this with? I have a feeling that the `graphql` dependency might just need updating but I can't tell

**Comment by rolurq** [comment]
@gschier sorry, I'm unable to provide the public endpoint :disappointed:

**Comment by rolurq** [comment]
@gschier Any updates on this?

**Comment by jeromedalbert** [comment]
The same thing happens to me on Insomnia 6.3.2. When I modify my GQL API, the API URL stays the same so there is no auto-refresh. I have to point-and-click to manually refetch the schema for warnings to disappear.

Refetching the schema somehow automatically, like in previous versions, would be nice in development, where I modify the schema in my codebase and test it straight away with Insomnia.

Or having a keyboard shortcut at least, so that people don't need to point-and-click to refresh their schemas.

**Comment by gschier** [comment]
Ya I think a way to enable periodic refresh would be good to add back

**Comment by seanwash** [comment]
@gschier or maybe a keyboard shortcut for refreshing a schema might be nice to have.

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

@seanwash or @jeromedalbert if you're still looking for this enhancement, feel free to check out the Ideas in GitHub Discussions.

**Comment by kreosus** [comment]
Hi @rolurq 
Do you see the same behavior with our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4
