### ISSUE TITLE
[Feature Request] update duplicate to allow to rename and move

### ISSUE THREAD

**Issue by robclancy** [Kong/insomnia#1627]
I never make a new request after the first one is made because I have my auth setup etc. I always duplicate instead. Would be very helpful if we could duplicate with options. So a modal with the name, some basic things could be changed maybe like the URL and method. And the location (maybe not location though because that is far less straight forward).

**Comment by gschier** [comment]
I can see providing the ability to change the name, since it's kind of a pain to do it after. However, for everything else, it seems like modifying it after duplication is just as easy. 

A good example of what you are asking is shown in IntelliJ when copying a file.

![image](https://user-images.githubusercontent.com/587576/62658295-77c0b000-b936-11e9-9961-79b7a1574d38.png)

**Comment by robclancy** [comment]
Yep. And another possible simple one which I think atom did (I don't use it anymore so can't check) is to duplicate like normal but have the `rename` activated over the file as if you had gone to rename and selected all the text.

**Comment by Pnoexz** [comment]
I'd like to see this feature implemented.
