### ISSUE TITLE
[Bug] Invalid JSON parse error when property is set to environment variable

### ISSUE THREAD

**Issue by dsacdalan** [Kong/insomnia#1658]
- Insomnia Version: 6.6.2
- Operating System: Windows 10

## Details

When a JSON property in the body of a request is set to an environment variable, a parse error incorrectly shows up: "Expecting 'STRING', '}' got '{'.

![image](https://user-images.githubusercontent.com/3640768/63890523-32315900-c9b1-11e9-9405-1dad1aae6326.png)

Note, the request still works but the error will always show.

## Steps to Reproduce

1. Create a new workspace
1. Create a new environment variable with any name and any value
1. Create a new request with a JSON body with one property and set the property's value to the environment variable

**Comment by gschier** [comment]
Ah yes, this is a limitation of using Nunjucks. As you can see, the actual JSON is:

```json
{
  "test": {{ testVar }}
}
```

which is invalid. There has been a running task since early on to write a custom linter (currently uses jsonlint) that handles Nunjucks tags but it's quite a large task to take on.

Note that this only happens with non-string literals. Wrapping the variable in quotes would not result in a lint error.

```json
{
  "test": "{{ testVar }}"
}
```

**Comment by dijiugeweiba** [comment]
I don't understand why this json format is invalid...
![2019-10-25](https://user-images.githubusercontent.com/21150257/67549788-a0876300-f737-11e9-8bf3-32d3ec63ccc3.png)
![2019-10-25 (1)](https://user-images.githubusercontent.com/21150257/67549857-c4e33f80-f737-11e9-8ddc-ced7a9118afb.png)

**Comment by gschier** [comment]
You need to use double quotes not single quotes
