### ISSUE TITLE
Environmental Variable imports from postman evaluate to "NaN"

### ISSUE THREAD

**Issue by Spirarel** [Kong/insomnia#1666]
## Bug

When you import environmental variables created in postman, any keys containing hyphens `-` evaluate to `NaN`
Ex:
```json
"api-key":"abc123"
```

### Versioning

- Insomnia Version: 6.6.2 (6.6.2.2932)
- Operating System: macOS 10.14.5

### Comments

This is probably related to #456

**Comment by goodeye** [comment]
See issue  #456

**Comment by Spirarel** [comment]
Hey goodeye,
Did you read the OP, where I referenced this very issue. An issue which I
commented on explaining there are common use-cases where this will be an
enduring problem?

**Comment by goodeye** [comment]
Oh, sorry - I didn't see the link at the bottom of your post! It seemed like this was a duplicate, and commentary was going on with 456. I agree it's a problem - that's how I found your post. (I should probably have said "See also issue...")

**Comment by Spirarel** [comment]
No worries, happens!

Hopefully, this gets some attention. It looked a little dire in that issue, but if Insomnia wants to be an alternative or replacement for Postman, it seems like a good thing to address.

**Comment by veritascs** [comment]
Bump, I created #1960 which is a duplicate (but I've closed it out so we can use this existing ticket).

* doesn't matter if you import from postman or not, any environmental key with a dash will fail
* still happening on v7.1.1

**Comment by DanAlexson90** [comment]
> See issue #456

Sadly closed.

**Comment by andreassiegel** [comment]
I just heard about Insomnia (I'm actually using Postman) and wanted to give it a try... At first, I was amazed by the opportunity to import both collections and environments from Postman! 🎉 

Unfortunately, nothing worked after that - just because of `-` in the names of environment variables, and all variables of my environments have names with dashes. That's really sad! 😞

**Comment by matheusmb** [comment]
Same issue here. Will it ever be fixed?

**Comment by nciske** [comment]
Same issue.

A bit disappointed to see there's still no fix after [3 years](https://github.com/Kong/insomnia/issues/456).

**Comment by rhukster** [comment]
Won't work with cloudflare API at all for this very reason.  "x-auth-email" won't allow `-` which is ludicrous. 

I was seriously considering this is a replacement for Postman, and one tiny regex fix would sort it.

**Comment by nijikokun** [comment]
Hi @rhukster,

Would an acceptable fix for this be to convert hyphenated variables imported from postman (`x-auth-email`) to pascal-case (`xAuthEmail`)?

The alternative workaround is that we create a filter to allow pulling hyphenated variables globally like shown here: https://github.com/11ty/eleventy/issues/567#issuecomment-575828788

Reason being that the underlying templating language (Nunjucks) treats hyphenated variable names as math logic (`x - auth - email`) instead of a singular lookup it attempts three and tries to subtract them from each other.

**Comment by rhukster** [comment]
I did a manually search and replace in the api json file converting the - (dashed) based keys to _ (underscores).  Then imported and that worked fine.   So ya I think at least while importing it’s a good workaround  to convert to camel/pascal case or underscored.  

Weirdly I noticed that with dashed syntax the preview when you add the token shows the correct value just not when you inspect or send. Not using nunchucks at that point? 

Also is there any specific reason for using a powerful template library like nunjucks? If this is merely used for simple curly bracket matching with token replacement, a regex would be faster and more interoperable. I guess if you rely on dot-notation for nesting, but even then that would not be hard to do custom. Are there other benefits I am missing?

**Comment by develohpanda** [comment]
Hi @rhukster, Insomnia plugins can create custom [template tags](https://support.insomnia.rest/article/40-template-tags). As such, nearly anything you see in the `ctrl + space` drop-down (encoding, prompts) and many plugins (eg [insomnia-plugin-faker](https://insomnia.rest/plugins/insomnia-plugin-faker)) actually integrate with Insomina through Nunjucks [custom tags](http://mozilla.github.io/nunjucks/api.html#custom-tags). The arguments to custom plugins, can be environment variables or raw data, and all of this is supported through Nunjucks.

For example, the `base64` custom tag can consume `baseurl`, an environment variable.

![image](https://user-images.githubusercontent.com/4312346/92921250-d33d6580-f487-11ea-9c59-f0c8bad68868.png)

It is entirely possible to write custom template logic as well!

![image](https://user-images.githubusercontent.com/4312346/92920941-3da1d600-f487-11ea-981c-b991caf9f570.png)

Nunjucks is quite a powerful template library, and is used in a powerful way 😄 I'm sure there are other ways to achieve similar results as well but Nunjucks is deeply rooted within the core Insomnia code-base.

In any case, I have created a draft PR that we will be working through in order to support hyphens - see #2601.

**Comment by rhukster** [comment]
Totally get it. I use Twig extensively in Grav so I appreciate that Nunjucks is used for more than it appeared to me at first glance. I’ll continue on the PR. Thanks!

**Comment by RaymondMwaura** [comment]
A fix for this could really help. Especially since Postman is unstable of late and requests fail there sporadically.

**Comment by develohpanda** [comment]
Hi @RaymondMwaura, this is published and should be working in the latest version of the app, 2021.7.0. Could you please share more details about what doesn't work for you and I'll help where I can?

**Comment by RaymondMwaura** [comment]
> Hi @RaymondMwaura, this is published and should be working in the latest version of the app, 2021.7.0. Could you please share more details about what doesn't work for you and I'll help where I can?

Hello @develohpanda ,

To recreate, import a Postman collection with the variables in kebab-case, such as "host-name". The environmental variable imports from postman evaluate to "NaN".

I am using the latest version of insomnia as follows:

![image](https://user-images.githubusercontent.com/17108099/149465858-5f462b43-a12a-4a98-a55a-6112dc88cdc5.png)
