### ISSUE TITLE
[Feature Request] Add configuration for Toggle Sidebar hotkey

### ISSUE THREAD

**Issue by a-p-o** [Kong/insomnia#1715]
- Insomnia Version: 7.01
- Operating System: macOS Catalina 10.15 (19A583)

## Details

Toggling the Sidebar is currently tied to the hotkey <kbd>⌘</kbd><kbd>\\</kbd>. A lot of applications use the <kbd>[</kbd> key or some variation (<kbd>⌘</kbd><kbd>[</kbd>, <kbd>⇧</kbd><kbd>[</kbd>, etc). It would be user-friendly to be able to edit the hotkeys for the actions under the menu bar.

Another use case is to avoid collisions with other hotkeys a user may have. For instance, 1Password's default hotkey for showing 1Password is also <kbd>⌘</kbd><kbd>\\</kbd>. When the hotkey is invoked, Insomnia does not toggle the sidebar.

**Comment by pawelgrzybek** [comment]
Hi @a-p-o.

I noticed the same thing that flexibility to change "Toggle Sidebar" disappeared from Insomnia. Luckily there is a way to override this shortcut using macOS keyboard preferences panel (tip for macOS users only though).

Hopefully that will help you out because for me it works like a charm :)

I changed it to `⌘ + b` because thats the one that I use a lot in Visual Studio Code to toggle sidebar. The default one collided with 1Password :-)

![Screenshot 2019-10-21 at 17 38 41](https://user-images.githubusercontent.com/3697104/67224798-e982a300-f429-11e9-8fdb-7f08684a0cd2.jpg)

**Comment by gschier** [comment]
Nice workaround!

The reason it disappeared is because there is currently not an easy way to have the global menu bar shortcuts be configured in the app. It was moved back to the menu bar because people were toggling the sidebar by accident and not being able to find how to untoggle. 

Now that I think about it though, we could remove the hotkey binding from the menu bar but leave the menu item there. Maybe I'll do that for now!

**Comment by jvfd3** [comment]
Thanks
