### ISSUE TITLE
[Bug] Filename not correct when saving response body to file

### ISSUE THREAD

**Issue by guptadd** [Kong/insomnia#1746]
- Insomnia Version: 6.6.2
- Operating System: Windows 10

## Details

When the response is a multipart file and it is saved to the disk, the filename appears to be generated with the help of current system time. While in Postman, the response is saved with the correct filename that is received in the response.

**Comment by gschier** [comment]
Can you provide screenshots of the response to demonstrate what it looks like?

**Comment by wongstein** [comment]
Closing this issue due to lack of acdtivity.

**Comment by ekeric13** [comment]
Hey so just bringing this issue back.

I will provide screenshots so the bug is more obvious:

Asks me to download photos
<img width="414" alt="Screenshot 2023-05-25 at 3 32 49 PM" src="https://github.com/Kong/insomnia/assets/6489651/3dbf95d6-6605-46a7-9e2d-0e1d95b5980b">

These are the headers
<img width="470" alt="Screenshot 2023-05-25 at 3 33 06 PM" src="https://github.com/Kong/insomnia/assets/6489651/c3df4844-1ae9-45c5-8deb-4db490ededc6">

When i download the file it doesn't take the filename
<img width="361" alt="Screenshot 2023-05-25 at 3 33 25 PM" src="https://github.com/Kong/insomnia/assets/6489651/985a8df7-c3c7-40ce-aa75-ea645886bf16">
