### ISSUE TITLE
Feature request: In json response show the size of array

### ISSUE THREAD

**Issue by vikrampaygude** [Kong/insomnia#1799]
- Insomnia Version: ___
- Operating System: ___

## Details

In json response preview please add a feature to show the size of the array. As in my case array size has to be compared to confirm correct output so I have copy and go other application to just get a count.
e.g 
![json array size](https://user-images.githubusercontent.com/19474255/69409988-10d1d600-0d30-11ea-8fbb-7a1e45689abd.png)

**Comment by gschier** [comment]
I really like the idea of this, and it's been requested before I think too. Since Codemirror is responsible for folding code, it's probably best to implement this as a Codemirror plugin. Maybe there's already one out there?

**Comment by develohpanda** [comment]
Hey @gschier, I'd like to pick this one up! 😄 

I forked [CodeMirror](https://github.com/codemirror/CodeMirror) and made a couple of additions to its `fold.brace` logic.

From what I could understand, it will be tricky to add the `// 3 items` as a comment without invalidating the JSON. There may be an add-on for this but I couldn't find one. Ignoring JSON invalidation, the implementation for commenting after a tag was getting unwieldy while I was experimenting as well.

In any case, I do think it would be nicer to add the count within the fold widget, instead of outside - that way there is one indicator and interaction point for folding, rather than two.

![](http://g.recordit.co/CERVzRaFoH.gif)

From a consumer perspective, you can currently override the fold widget. I introduced an `itemsWidget` field. I chose to separate the field so that the existing is kept as a fallback. 

![image](https://user-images.githubusercontent.com/4312346/69489768-99907380-0ee2-11ea-976b-8d9b1ca562df.png)

This `itemsWidget` only kicks in, in the case we have a **valid** item count. For example, with invalid JSON, the default fold widget `<->` is used to preserve existing behavior.

![](http://g.recordit.co/WeedYIqJkh.gif)

Pending review in CodeMirror, but I figured I'd get my thoughts and decisions into words while they are fresh. 😄

**Comment by develohpanda** [comment]
Looks like my PR was merged in after some suggestions. Once it [this](https://github.com/codemirror/CodeMirror/commit/3ace5da283db612d0d43211fd0df97499287aeb8) gets deployed to CodeMirror I'll come back and update Insomnia 😄

**Comment by gschier** [comment]
Woah, that's awesome @develohpanda! That's a huge project to get a contribution into 🙌🏻

Yes, feel free to create a PR to bump the codemirror version once it's released 💫

**Comment by develohpanda** [comment]
Hey thanks @gschier! It's an interesting project, very very vanilla js and so simple to get running.

I'm going to see how I might be able to contribute to codemirror.next - v6 rewritten in typescript!

**Comment by gschier** [comment]
Nice, I'm super excited for v6 to launch
