### ISSUE TITLE
How to parse Response body (json string)

### ISSUE THREAD

**Issue by gomobig** [Kong/insomnia#1830]
[Question] – How to parse Response body (json strings) with jsonpath!

- Insomnia Version: 7.0.1
- Operating System: macOS 10.15.1

## Details
response body is :
 {"version":"1.0", "result":"[{\"id\":2}]"}
how could I preview result with pretty json like 
[
  {
    id: 2
  }
]

**Comment by gschier** [comment]
It's not currently possible to use JSONPath filters on stringified JSON.

Perhaps one way to enable this would be to update the plugin system to allow a plugin to transform responses. Then, for example, you could write a small plugin to turn this

```json
{"version":"1.0", "result":"[{\"id\":2}]"}
```

Into this

```json
{"version":"1.0", "result": [{"id":2}] }
```

So that Insomnia could operate on the JSON response.

Thoughts?

**Comment by gomobig** [comment]
thanks!  i pretreatment the response data with responseHooks, rewrite the response body, now it work well for me.

**Comment by gschier** [comment]
Awesome! 😄
