### ISSUE TITLE
[Feature Request] Search in documentation

### ISSUE THREAD

**Issue by Macavirus** [Kong/insomnia#1864]
**Is your feature request related to a problem? Please describe.**
Graphql documentation explorer is impossible to navigate with hundreds of possible queries.

**Describe the solution you'd like**

Search in the text of the documentation explorer

**Describe alternatives you've considered**
Altair, for one does this.

**Comment by Macavirus** [comment]
This is still a terrific feature that would make Insomnia a superior tool to Altair and GraphiQL

**Comment by baldwindavid** [comment]
I still have to supplement Insomnia with GraphiQL for searching documentation. GraphiQL provides a persistent documentation area that doesn't reset every time something happens in the query window like Insomnia.

Really, it would be nice if there were a persistent sidebar that could be toggled on the right displaying searchable documentation rather than the current ephemeral popup.

Insomnia is great, but I'd like it to be the only tool I need to work with GraphQL.

**Comment by dimitropoulos** [comment]
Just to make sure: https://github.com/Kong/insomnia/pull/3388 recently merged.  Is what you're asking for something different than that?

**Comment by baldwindavid** [comment]
@dimitropoulos Oh, awesome! I noted some asides about documentation resetting and I'm not sure if that is covered. Regardless, this feature request was pertaining to search and it appears #3388 introduces it, so it seems that this will be able to be closed. I'm looking forward to using it. Thanks!

**Comment by dimitropoulos** [comment]
sweet.  and hey, as always, if there's something you'd like to be improved about it let us know!  not sure about the resetting, so when can, please try it out and let us know.  "easy to use" is always our goal, and we're excited about this feature, too.
