### ISSUE TITLE
[Usability] Dash in environment config key resolves value to `NaN`

### ISSUE THREAD

**Issue by Moeriki** [Kong/insomnia#456]
- Insomnia Version: Version 5.7.14 (5.7.14.1021)
- Operating System: macOS 10.13 Beta (17A352a)

## Details

Environment keys containing dash `-` resolve their value to `NaN`.

**Base environment**

```
{
  "mykey": "myvalue",
  "my-key": "my-value"
}
```

**URL**

    http://{{ mykey  }}/{{ my-key  }}

**URL PREVIEW**

    http://myvalue/NaN

**Comment by gschier** [comment]
Hmm, I swear there was an issue on this before but I can't find it. 

There is currently a warning that shows up after editing an environment if one of your variables contains dashes. This is because nunjucks (the rendering engine Insomnia uses) interprets this as subtraction (ie. `{{ my - key }}`). Maybe a more prominent message is needed?

![image](https://user-images.githubusercontent.com/587576/29635779-ea9c05fa-8802-11e7-88cc-e77980699ce3.png)

**Comment by Moeriki** [comment]
After updating I have this visual message al well.

Good enough.

**Comment by seangarner** [comment]
I ran into this today testing insomnia as a potential replacement for postman for my small team.  I feel like somewhat of a goon having now actually read the error message, but I did just spend 10 minutes trying to figure out what was going on and only found the solution when going to file a bug and finding this first.

Perhaps it's because I saw it as a warning message rather than an error?  I expect errors to be red, not orange, and it seems a little weird that it'd even let me save a config it knows it's broken.  Wouldn't it be better to disable the "Done" button while it's invalid?

**Comment by gschier** [comment]
@seangarner it's a warning because technically there _are_ use cases where a dash is acceptable.

One way to make this better might be to treat the scenario as an error but provide an "I know what I'm doing" button to dismiss the error in the future. Thoughts?

**Comment by seangarner** [comment]
Yes that'd work well @gschier.

I'm very curious what the use case for doing maths in a property name is. :thought_balloon:

**Comment by gschier** [comment]
Well, it's only math if you use it as a variable like `{{ foo-bar }}`. You may want dashes in a key name for other reasons, like if you wanted to store free-form JSON in your environment that happens to use dashes. Plugins can also reference the environment, which may or may not use dashed key names for the use case.

There definitely aren't very many use cases, but even if there's only a small chance that it might be useful, I don't want to fully prevent it from happening.

**Comment by Cricen** [comment]
had the same issue using "api-token" my post was then sending `NaN`. At least now I know a work around which is to use apiToken

**Comment by 4ekki** [comment]
@gschier , this one is actual in 6.5.4 and there is no [such warning](https://github.com/getinsomnia/insomnia/issues/456#issuecomment-324445933) shown
![image](https://user-images.githubusercontent.com/38757986/60883066-dcaeba80-a251-11e9-8c3b-3611564cae1e.png)

**Comment by taylorgoolsby** [comment]
@gschier I just ran into this problem. No error or warning message is shown.

**Comment by robross0606** [comment]
Same here on latest version.  There are no errors when setting up environment, but the resolution is "NaN".

**Comment by HimbeersaftLP** [comment]
Can confirm, too

**Comment by larsfjelstad** [comment]
Is there any workaround to this? A way to escape the dash?

**Comment by maxpiepenbrink** [comment]
I ran into this today and was extremely confused by it, only this post lead me to understanding what I was doing wrong.

**Comment by mantono** [comment]
This problem still persists in version **7.0.1**.

**Comment by sn0wil** [comment]
Hi guys! Is there something to expect for fixing the issue with keys, written with dash? In **7.0.3** if I write key with dashes it will be replaced with **NaN**. Should I rewrite all params in camelCase or without dashes? 


![image](https://user-images.githubusercontent.com/31205951/68224738-3c4e8400-0000-11ea-8fc1-3d206fdd5e88.png)
--- 
![image](https://user-images.githubusercontent.com/31205951/68224751-41abce80-0000-11ea-8fb2-a201f88cd0d4.png)

**Comment by james-work-account** [comment]
I am still getting variables resolving to NaN, when the environment variables have hyphens in them in **v7.0.3**.

**Comment by oussaka** [comment]
Same problem in v7.0.5

**Comment by gschier** [comment]
Due to using Nunjucks as the underlying template engine, there is no way to support names with dashes. 

The UI should be updated to ensure the user cannot make this mistake by accident.

**Comment by maladon** [comment]
Ditto @gschier 's post. The ui should block this. Wasted an hour fiddling with this (insomnia newbie)...

**Comment by james-work-account** [comment]
@gschier maybe also a warning when importing data that contains names with dashes too. That's where I was stuck for half a day, since I didn't get the warning you mentioned in a previous comment having imported data rather than created the variables myself.
Not sure how difficult that would be to implement, mind you.

**Comment by veritascs** [comment]
Guys, comment under #1666 because it's still open. Cheers!

**Comment by DragosMocrii** [comment]
This is a ridiculous limitation

**Comment by develohpanda** [comment]
Re-opening this as a potential fix is in the works (#2601), and there was a lot of activity on this (and duplicate) issues. 😄
