### ISSUE TITLE
[Bug] OAuth 2 Authorization Code issue with Insomnia newer version

### ISSUE THREAD

**Issue by tourili** [Kong/insomnia#794]
- Insomnia Version: v5.14.9
- Operating System: Windows 10

## Details

Hi
I am having issue with OAuth 2.
Now looks like only implicit grant type that is working but never with authorization code. I used it before I upgrade (few months ago) and the Refresh token was always retrieved properly on Azure AD

Here are some debug info:

> [oauth2] Ignoring URL "https://login.microsoftonline.com/dcfabrik.onmicrosoft.com/oauth2/authorize…DcyNGQwMjk1IiwiVElEIjoiOTI1Y2QxMmEtNjI4NC00YmFjLWIxNzYtMzUwNDI1NzFmMTkzIn0". Didn't match /https:\/\/insomnia\.rest\/.*(code=)/i
> 
> [oauth2] Matched success redirect to "https://insomnia.rest/?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjE…6tflXkCUuOxDDK6_AVOP0ougLXYfZc4mSAJu3Z_-vqoXAeDWKfA._d4-L5Z1lDiE4F8gxVUvzQ" with /https:\/\/insomnia\.rest\/.*(code=)/i
> 
> [oauth2] Detected redirect https://insomnia.rest/?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjE…6tflXkCUuOxDDK6_AVOP0ougLXYfZc4mSAJu3Z_-vqoXAeDWKfA._d4-L5Z1lDiE4F8gxVUvzQ

And this end up on token failure on Insomnia as Bad Request:

> [oauth2] Failed to fetch token url=https://login.microsoftonline.com/dcfabrik.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1_signin status=400

It was working in oldets version...

**Comment by gschier** [comment]
That's strange. If it got to `detected redirect...` it should have worked. I will take a look

**Comment by gschier** [comment]
One thing you might want to try is switching the credentials type to see if that fixes it for you. I will also add the response body to that log message so you can hopefully see the error message.

![image](https://user-images.githubusercontent.com/587576/37943010-97405a6a-312a-11e8-994b-0c91a90498db.png)

**Comment by ThePJMP** [comment]
I'm on version 6.0.2.2311 and still presenting this problem too.

**Comment by p-m-j** [comment]
Appears to still be an issue in 2020.5.2

Edit:

Right, I have app building locally, response body doesn't seem to be logged for errors but with debugger attached I see this 


```
{
    "error": "invalid_request",
    "error_description": "AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.\r\nTrace ID: d3c901ef-89b2-486a-98e6-caef280e4400\r\nCorrelation ID: ce2c3e7a-92a3-44d4-81ac-a3739a575a49\r\nTimestamp: 2021-02-03 14:51:37Z",
    "error_codes": [9002327],
    "timestamp": "2021-02-03 14:51:37Z",
    "trace_id": "d3c901ef-89b2-486a-98e6-caef280e4400",
    "correlation_id": "ce2c3e7a-92a3-44d4-81ac-a3739a575a49"
}
```

Edit 2:

Works perfectly if I add the following header in grant-authorization-code.js, not sure what a nice fix is for this, another input in advanced options for origin header?

```
    { name: 'Origin', value: 'http://localhost:3000' },
```

**Comment by DMarby** [comment]
Hi @rustybox, thank you for looking into this!

Just to clarify, the issue you are running into is that since the Origin header is not set, and the oauth provider requires CORS, the authorization code exchange fails?
What oauth provider are you using, and where in `grant-authorization-code.js` did you add the Origin header to make it work?

**Comment by p-m-j** [comment]
Indeed, Origin header is not set resulting in a 400 for the request to the token endpoint for Azure AD (v2) https://login.microsoftonline.com/{{tennant_id}}/oauth2/v2.0/token

I added the origin header to the array in _getToken line ~156 on develop branch
This stopped the 400 and results in successful retrieval of access and refresh tokens.

I do wonder if a change for #401 would be a better solution as it allows flexibility for any ad hoc header requirements rather than solving for this specific case.

Additionally it'd be really useful if the response body was output in the "Response Timeline" console that shows if you click the little green bug to help others diagnose issues in the future.

Edit: 
This is when creating an "App Registration" with a "SPA Platform" in Azure AD parlance, essentially setup for browser based auth_code flow with PKCE

**Comment by DMarby** [comment]
@rustybox Being able to set custom headers does indeed seems like a sensible approach to resolve this and other similar issues! 

I have reopened #401
