### ISSUE TITLE
[Feature Request] Multiline editing for all inputs

### ISSUE THREAD

**Issue by strarsis** [Kong/insomnia#865]
In some exotic/rare cases a client may send the data as form field name (empty value).
It would be nice if Insomnia also supports very long form field names with multiline.

**Comment by strarsis** [comment]
This is not stale. This feature is useful and may be required for some use cases.

**Comment by gschier** [comment]
In general, I agree. I think that if we're talking about being able edit multi-line inputs than it probably makes the most sense to apply multi-line editing to **all** inputs in the app, with a consistent method of access.

Since this feature is fairly niche and I want to keep Insomnia's UI as simple as possible, I suggest adding it as a hidden shortcut (maybe Ctrl-Click or under a keyboard shortcut?). I'm open to suggestions.

**Comment by gschier** [comment]
I like the context-menu idea 👍

**Comment by strarsis** [comment]
Not stale!

**Comment by Jaap-van-Hengstum** [comment]
I would like to have multiline support for template tag values. For example, base64 encode a multiline string. Will this feature request cover this also?
